version: '2'

services:
  cartdb:
   image: postgres:9.4
   environment:
     - POSTGRES_USER=cart
     - POSTGRES_PASSWORD=cart
   ports:
     - "5432:5432"

  brokerdb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=pact_broker
      - POSTGRES_PASSWORD=pact_broker
    volumes:
      - brokerdb:/var/lib/postgresql
    ports:
      - 5432

  broker:
    image: dius/pact-broker
    environment:
      - PACT_BROKER_DATABASE_USERNAME=pact_broker
      - PACT_BROKER_DATABASE_PASSWORD=pact_broker
      - PACT_BROKER_DATABASE_HOST=brokerdb
      - PACT_BROKER_DATABASE_NAME=pact_broker
    ports:
      - "8085:80"

volumes:
  brokerdb:
